/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int EXP = 9;
  /** RegularExpression Id. */
  int RAD = 10;
  /** RegularExpression Id. */
  int PARENTHESIS_LEFT = 11;
  /** RegularExpression Id. */
  int PARENTHESIS_RIGHT = 12;
  /** RegularExpression Id. */
  int BRACKET_LEFT = 13;
  /** RegularExpression Id. */
  int BRACKET_RIGHT = 14;
  /** RegularExpression Id. */
  int KEY_LEFT = 15;
  /** RegularExpression Id. */
  int KEY_RIGHT = 16;
  /** RegularExpression Id. */
  int CONSTANT = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"//\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\";\"",
  };

}
